FROM python

# Install the requirements

COPY requirements.txt /tmp/requirements.txt
RUN pip install -r /tmp/requirements.txt

# Copy the code
COPY . /app
WORKDIR /app

# Run the scraper
CMD ["python", "scraper.py"]